/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as ApiPublicStatusRouteImport } from './routes/api/public/status'
import { Route as ApiPublicApplicationsRouteImport } from './routes/api/public/applications'
import { Route as AuthenticatedApplicationsIdRouteImport } from './routes/_authenticated/applications.$id'
import { Route as ApiPublicPaymentVerifyRouteImport } from './routes/api/public/payment/verify'
import { Route as ApiPublicPaymentInitiateRouteImport } from './routes/api/public/payment/initiate'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicStatusRoute = ApiPublicStatusRouteImport.update({
  id: '/api/public/status',
  path: '/api/public/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApplicationsRoute = ApiPublicApplicationsRouteImport.update({
  id: '/api/public/applications',
  path: '/api/public/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationsIdRoute =
  AuthenticatedApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const ApiPublicPaymentVerifyRoute = ApiPublicPaymentVerifyRouteImport.update({
  id: '/api/public/payment/verify',
  path: '/api/public/payment/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentInitiateRoute =
  ApiPublicPaymentInitiateRouteImport.update({
    id: '/api/public/payment/initiate',
    path: '/api/public/payment/initiate',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/api/public/applications': typeof ApiPublicApplicationsRoute
  '/api/public/status': typeof ApiPublicStatusRoute
  '/api/public/payment/initiate': typeof ApiPublicPaymentInitiateRoute
  '/api/public/payment/verify': typeof ApiPublicPaymentVerifyRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/api/public/applications': typeof ApiPublicApplicationsRoute
  '/api/public/status': typeof ApiPublicStatusRoute
  '/api/public/payment/initiate': typeof ApiPublicPaymentInitiateRoute
  '/api/public/payment/verify': typeof ApiPublicPaymentVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/api/public/applications': typeof ApiPublicApplicationsRoute
  '/api/public/status': typeof ApiPublicStatusRoute
  '/api/public/payment/initiate': typeof ApiPublicPaymentInitiateRoute
  '/api/public/payment/verify': typeof ApiPublicPaymentVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/applications'
    | '/customers'
    | '/notifications'
    | '/payments'
    | '/queue'
    | '/settings'
    | '/applications/$id'
    | '/api/public/applications'
    | '/api/public/status'
    | '/api/public/payment/initiate'
    | '/api/public/payment/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/applications'
    | '/customers'
    | '/notifications'
    | '/payments'
    | '/queue'
    | '/settings'
    | '/'
    | '/applications/$id'
    | '/api/public/applications'
    | '/api/public/status'
    | '/api/public/payment/initiate'
    | '/api/public/payment/verify'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/analytics'
    | '/_authenticated/applications'
    | '/_authenticated/customers'
    | '/_authenticated/notifications'
    | '/_authenticated/payments'
    | '/_authenticated/queue'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/applications/$id'
    | '/api/public/applications'
    | '/api/public/status'
    | '/api/public/payment/initiate'
    | '/api/public/payment/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicApplicationsRoute: typeof ApiPublicApplicationsRoute
  ApiPublicStatusRoute: typeof ApiPublicStatusRoute
  ApiPublicPaymentInitiateRoute: typeof ApiPublicPaymentInitiateRoute
  ApiPublicPaymentVerifyRoute: typeof ApiPublicPaymentVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/status': {
      id: '/api/public/status'
      path: '/api/public/status'
      fullPath: '/api/public/status'
      preLoaderRoute: typeof ApiPublicStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/applications': {
      id: '/api/public/applications'
      path: '/api/public/applications'
      fullPath: '/api/public/applications'
      preLoaderRoute: typeof ApiPublicApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/applications/$id': {
      id: '/_authenticated/applications/$id'
      path: '/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AuthenticatedApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/api/public/payment/verify': {
      id: '/api/public/payment/verify'
      path: '/api/public/payment/verify'
      fullPath: '/api/public/payment/verify'
      preLoaderRoute: typeof ApiPublicPaymentVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment/initiate': {
      id: '/api/public/payment/initiate'
      path: '/api/public/payment/initiate'
      fullPath: '/api/public/payment/initiate'
      preLoaderRoute: typeof ApiPublicPaymentInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedApplicationsRouteChildren {
  AuthenticatedApplicationsIdRoute: typeof AuthenticatedApplicationsIdRoute
}

const AuthenticatedApplicationsRouteChildren: AuthenticatedApplicationsRouteChildren =
  {
    AuthenticatedApplicationsIdRoute: AuthenticatedApplicationsIdRoute,
  }

const AuthenticatedApplicationsRouteWithChildren =
  AuthenticatedApplicationsRoute._addFileChildren(
    AuthenticatedApplicationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRouteWithChildren
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRouteWithChildren,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicApplicationsRoute: ApiPublicApplicationsRoute,
  ApiPublicStatusRoute: ApiPublicStatusRoute,
  ApiPublicPaymentInitiateRoute: ApiPublicPaymentInitiateRoute,
  ApiPublicPaymentVerifyRoute: ApiPublicPaymentVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
